name: Build Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    # Runs everyday at 1:00 AM UTC
    - cron: "0 1 * * *"
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # 使用一个稳定的 LTS 版本

      - name: Install dependencies
        # 不再使用全局安装，而是安装到本地 node_modules，这是更好的实践
        run: npm install javascript-obfuscator

      - name: Clone BPB worker js
        run: |
          # 增加错误处理，如果下载失败则任务失败
          wget -O origin.js https://github.com/bia-pain-bache/BPB-Worker-Panel/releases/download/v3.6.1/worker.js || (echo "Failed to download the source file." && exit 1)
      
      - name: Create Obfuscator Config
        # 将复杂的配置写入一个 JSON 文件，方便管理
        run: |
          echo '{
            "compact": true,
            "controlFlowFlattening": true,
            "controlFlowFlatteningThreshold": 1,
            "deadCodeInjection": true,
            "deadCodeInjectionThreshold": 1,
            "debugProtection": true,
            "debugProtectionInterval": 4000,
            "disableConsoleOutput": true,
            "identifierNamesGenerator": "hexadecimal",
            "log": false,
            "numbersToExpressions": true,
            "renameGlobals": false,
            "selfDefending": true,
            "simplify": true,
            "splitStrings": true,
            "splitStringsChunkLength": 10,
            "stringArray": true,
            "stringArrayCallsTransform": true,
            "stringArrayEncoding": ["rc4"],
            "stringArrayIndexShift": true,
            "stringArrayRotate": true,
            "stringArrayShuffle": true,
            "stringArrayWrappersCount": 5,
            "stringArrayWrappersChainedCalls": true,
            "stringArrayWrappersParametersMaxCount": 5,
            "stringArrayWrappersType": "function",
            "stringArrayThreshold": 1,
            "transformObjectKeys": true,
            "unicodeEscapeSequence": false
          }' > obfuscator.json

      - name: Obfuscate BPB worker js (First Pass)
        run: |
          # 使用 npx 执行本地安装的包，并引用配置文件
          npx javascript-obfuscator origin.js --config obfuscator.json --output pass1.js

      - name: Obfuscate BPB worker js (Second Pass for added complexity)
        # 第二轮混淆，使用不同的、更侧重于结构破坏的配置
        run: |
          npx javascript-obfuscator pass1.js \
          --output _worker.js \
          --compact true \
          --self-defending true \
          --string-array true \
          --string-array-encoding 'base64' \
          --split-strings true \
          --split-strings-chunk-length 5

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':zap: Chore: Update obfuscated worker script'
          commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'

